### ISSUE TITLE
Не отображается фото после сохранения

### ISSUE THREAD

**Issue by ZubikIT** [ferdiunal/nova-settings#2]
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/9095d4b5-86a6-4eea-815a-289672424912">

Пакет как раз искал такого рода, спасибо очень помог.

Подскажите как сделать что бы отображалось фото?
В БД путь сохранился и файл есть в файловой системе но не отображается
<img width="974" alt="image" src="https://github.com/user-attachments/assets/443d28ff-ddbc-4f6f-a3e2-7529a64a7ad9">

**Comment by ferdiunal** [comment]
Hi,
I'm glad you like the package. I haven't encountered any problems with the image not displaying in my own tests. I suggest you do the following checks:
Is the **APP_URL** in the .env file correct?
Run the **php artisan storage:link** command,
Checking folder permissions.
Since my development environment is Sail, I did my tests with VaporImage field using MinIO. After your message, I also tried Image field and did not see any problem.

Please write if there is anything else I can help you with. I created this [repo](https://github.com/ferdiunal/nova-settings-test) to help.
